---
title: "Using 'prettybreaks'"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using 'prettybreaks'}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = FALSE,
  fig.width = 7,
  fig.height = 6
)
```

## Introduction

`prettybreaks` contains functions to create pretty breaks for numeric vectors. 

Its main function `pretty2()` is similar to `base::pretty()` but allows to use different number systems and other tweaks, see examples below.

The algorithm is based on [1].

## Installation

```
library(devtools)
install_github("mayer79/prettybreaks")
```

## Examples

```{r}
library(prettybreaks)

x <- 1:100

pretty2(x)                           # c(0, 20, 40, 60, 80, 100)
pretty2(x, n = 4)                    # c(0, 50, 100, 150)
pretty2(x, base = 5)                 # c(0, 25, 50, 75, 100)
pretty2(x, p = c(10/7, 20/7, 50/7))  # c(0., 28.57143, 57.14286, ...)

```

## References

[1] W. J. Dixon and R. A. Kronmal (1965). The choice of origin and scale for graphs. Journal of the ACM, 12(2):259-261.
